### ISSUE TITLE
Geography dataset does not alias derived tables consistently

### ISSUE THREAD

**Issue by DeNeutoy** [jkkummerfeld/text2sql-data#17]
The Geography dataset contains examples where a derived table is aliased without using the "AS" keyword. There are 25 examples of this in the dataset which you can find by `CTRL-F` ") DERIVED" in the json file. Although this is still valid SQL, it would be nice if it was reformatted, because it is inconsistent with the column aliasing throughout the rest of the datasets.

Here is a line which demonstrates the issue: https://github.com/jkkummerfeld/text2sql-data/blob/master/data/geography.json#L3099

**Comment by jkkummerfeld** [comment]
Thanks, I've fixed this in a commit to the data development branch (see https://github.com/jkkummerfeld/text2sql-data/commit/46846d1ed023deaab06d08669a67d7eda631f2b5 ). Since it's not a major issue I'll wait until we have more updates before merging it in to master (these changes to data necessitate a version number change, which we want to do infrequently to avoid chaos in comparisons).

**Comment by DeNeutoy** [comment]
Oh awesome, I didn't see that. Thanks!!
