### ISSUE TITLE
WikiSQL

### ISSUE THREAD

**Issue by alexpolozov** [jkkummerfeld/text2sql-data#4]
Hello,

First, thanks a lot for taking time to standardize all these datasets and publishing the analysis! It's super helpful.

I noticed that in the paper you mention WikiSQL as one of the community datasets, you include it in the redundancy analysis, but then you don't include it in the comparison of results and this repository also doesn't have a standardized version of WikiSQL. Are there any plans to include it in the next version? Thanks.

**Comment by jkkummerfeld** [comment]
Hi,
We did not include WikiSQL in the second half of the paper because while it has redundancy in query patterns (as described in the paper), it does not have the redundancy used to construct the query split (which maintains table names).

That said, standardising the format to match would be nice! We are busy preparing for ACL (and traveling), but will keep this issue open to look at.

Thanks!

**Comment by todpole3** [comment]
Would love to see the standardized WikiSQL as an addition to the current data as well.

**Comment by jkkummerfeld** [comment]
@todpole3 and @alexpolozov I've added a draft conversion of WikiSQL in the data-development branch (https://github.com/jkkummerfeld/text2sql-data/tree/data-development), which you can access directly here:

https://github.com/jkkummerfeld/text2sql-data/blob/data-development/data/wikisql.json.bz2?raw=true

If you check it out and find any issues please let me know!

**Comment by jkkummerfeld** [comment]
Closing as we have now merged in the branch that contains WikiSQL.
